[package]
name = "evm_rust_decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
ethabi = "18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ethereum-types = "0.14"
